### ISSUE TITLE
login redirects to 127.0.0.1

### ISSUE THREAD

**Issue by akawoj** [azai91/alfred-drive-workflow#10]
Can't login and configure plugin.

**Comment by azai91** [comment]
What step in the login workflow does not work for you?

**Comment by akawoj** [comment]
I've had problems with configure login token, but after few tries it worked. Please close this issue.

**Comment by azai91** [comment]
Thanks! Closing issue. Please star the repo if you found it useful!

**Comment by skotzko** [comment]
I'm having the same issue. After I approve access to my account in Google, it comes back to localhost and doesn't work. I tried to run `python server.py` in the workflow dir (from [this issue](https://github.com/azai91/alfred-drive-workflow/issues/5)) and no output at all to console.

**Comment by azai91** [comment]
The page freezes because we are requesting all your files and storing in cache. I requested the server shutoff after 30 seconds, which somtimes causes the page not to work. I will increase the timeout. The workflow should still work regardless of the timeout issue. Let me know if it doesn't.

**Comment by skotzko** [comment]
Ah, it does, didn't realize. It does work. Sorry for the false alarm.
ᐧ

**Comment by xszconfig** [comment]
Login is very slow and the page cannot freeze for a long time. Please improve that.
