### ISSUE TITLE
[request] Create new doc from alfred

### ISSUE THREAD

**Issue by ilyador** [azai91/alfred-drive-workflow#11]
Would be cool

**Comment by azai91** [comment]
that is a great feature. I will work on that.

**Comment by azai91** [comment]
just added to latest version. create a doc by typing in "d > create google doc." please try it out and let me know what you think.

**Comment by ilyador** [comment]
Where do I download it? There is no workflow file in the repo

**Comment by azai91** [comment]
https://github.com/azai91/alfred-drive-workflow/releases/tag/v1.2

**Comment by Jawwads** [comment]
Great work, @azai91. Creating new doc is nice. It would be great if we could do something like "d n s [name]" to create a new google sheet. [d to initiate, n to new, s to sheets, and [name to file name]
