### ISSUE TITLE
Oauth is broken

### ISSUE THREAD

**Issue by blendahtom** [azai91/alfred-drive-workflow#16]
https://accounts.google.com/o/oauth2/auth?access_type=offline&approval_prompt=force&scope=https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdrive+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdrive.appdata+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdrive.file&response_type=code&redirect_uri=http%3A%2F%2F127.0.0.1%3A1337&client_id=978117856621-tvpnqtr02b8u0bgnh75sqb1loq1f5527.apps.googleusercontent.com&from_login=1&as=506805322a69085d&authuser=0

d > login doesn't work :(

**Comment by chrisspiegl** [comment]
Looks like I am having the same problem.

The local server at 1337 does not seem to run (at least the redirect to go there from Google does not work).

Please help? I'd love to use this plugin.

**Comment by azai91** [comment]
Can you attempt to login (`d > login` in alfred) and then run `lsof -i -P | grep -i "listen" | grep 1337` in your terminal. Let me know if you get an output from the terminal.

**Comment by chrisspiegl** [comment]
For me it worked one day later. So I am not sure what the problem was. Maybe I had to restart my computer or something.

**Comment by truejaian** [comment]
Having same issue (my issue looks like the same as the screencast here: https://github.com/azai91/alfred-drive-workflow/issues/9) 

Here are the results of the listen command:

`lsof -i -P | grep -i "listen" | grep 1337

Python    28306 Danny    5u  IPv4 0xd199bca7bfffcabd      0t0  TCP localhost:1337 (LISTEN)
Python    28328 Danny    5u  IPv4 0xd199bca7bfffcabd      0t0  TCP localhost:1337 (LISTEN)`

Also no debug information shows in the Alfred deugger set at log all information.

This is one of the most useful workflows and it's a bit of a bummer :(.

Also received success message.
![image](https://cloud.githubusercontent.com/assets/1806397/19128059/7e139e0c-8af6-11e6-9c60-55601f5bf9cd.png)

Tried 
- reinstalling Workflow with latest release
- re logging in
- clearing cache
- changing to argument required
- change keyword

Thanks for your help!

**Comment by pkuczynski** [comment]
I am getting `socket.error: [Errno 48] Address already in use`. Not sure how can I fix that?

**Comment by sorbits** [comment]
Please upgrade to [version 2.0](https://github.com/azai91/alfred-drive-workflow/releases/latest).

The authentication code has been rewritten and should be much more robust.
