### ISSUE TITLE
Include folders in search results, and put them at the top

### ISSUE THREAD

**Issue by rootwork** [azai91/alfred-drive-workflow#17]
Great work on this!

I have a lot of folders in my drive, but this doesn't seem to include folder titles, just the documents inside them. It would be great if the search included folder titles. (If you think some people would dislike this, then maybe add it as a configuration setting.)

Additionally, if folders were added, it'd be nice to put matching ones up at the top of results.

Thanks!

**Comment by Jawwads** [comment]
+1 

It would be nice if we can have a separate command for folder searches. Maybe, "d f [search_term]". 

Thanks alot for your volunteer work, @azai91 👍

**Comment by montemartin** [comment]
Also agree. A way to view folders would be terrific.
