### ISSUE TITLE
Add metadata in description

### ISSUE THREAD

**Issue by rootwork** [azai91/alfred-drive-workflow#18]
I'm not sure what Alfred calls the second line of each item, but here's what I mean by "description," using forecast as an example:

![screen shot 2016-06-13 at 10 33 17 am 2](https://cloud.githubusercontent.com/assets/79733/16016961/6a932f4e-3152-11e6-81a8-678e9fadeea2.png)

It'd be great if that line could include metadata such as:
- last modified date
- creation date
- whether it's my file or shared with me
- parent folder

I'm not sure how best to format those or if they'd all fit, but having _some_ of that information displayed -- at the very least last-modified -- would be really helpful.

Thanks for this helpful workflow!

**Comment by azai91** [comment]
sounds great - will work on this weekend
