### ISSUE TITLE
[Request] Sort by recently viewed

### ISSUE THREAD

**Issue by amscher** [azai91/alfred-drive-workflow#19]
When I'm search drive, it searches all docs that have been shared with me, which much of the time isn't useful. It'd be great if they were displayed in order of recency. 

Also, if there are no search results, I'd like to be able to hit enter and have it search drive for the same string. Sometimes docs won't show up in the search results for this workflow, but they do when I manually search in drive.

**Comment by azai91** [comment]
That's a great idea. I will on that later this weekend.

**Comment by amscher** [comment]
Hey there, wondering if you've made any progress on this! Would still love it :) This is my favorite workflow.

**Comment by schurpf** [comment]
+1

**Comment by sorbits** [comment]
I’ve made a PR which includes 57494ae8fed03b049e20a8c9798b854a2e96a769.

It won’t use Google Drive’s “last recently used” but instead sort them based on Alfred’s own ranking, which includes a “last recently used [from Alfred]”. I think this behavior makes sense.

**Comment by sorbits** [comment]
> Sometimes docs won't show up in the search results for this workflow, but they do when I manually search in drive.

This workflow is using a cache for Google Drive items, the default expiration time is a full month, which is probably why you are missing items.

I did a major overhaul of the workflow (PR #31) which will expire the cache after 10 minutes, so I think with this change, you should not see the problem anymore.

If you still see the problem (using my updated workflow) please open a separate issue.
