### ISSUE TITLE
Python process occupies 100% of a core

### ISSUE THREAD

**Issue by StefanHennig** [azai91/alfred-drive-workflow#21]
Once using the Alfred command "d" the python process permanently occupies 100% of a processor core. Only killing the python process helps. Seems there is an endless loop...?!

I am using macOS Sierra 10.12.4 Beta and Python 2.7.10 is in the path.

**Comment by jul-sh** [comment]
Same happening for me too :(, my fans usually jump to being really loud. Sometimes I get multiple instances of the python process as well, even on beta 5. I would love a fix for this, it's honestly my favourite workflow and I'm pretty bummed that I had to disable it.

**Comment by jul-sh** [comment]
FYI, version =<0.6 seems ok, the issue only appears later. v0.6 is quite usable for me, that's what's my daily driver now. Must be an issue with the external process.
(update, the issues occurs with .6 as well)

**Comment by mario-hab** [comment]
Same here. The "d FILENAME" command causes Alfred to use 100% of one CPU core. When killing Alfred, a Python task remains that still uses 100% CPU.

Are there any suggestions by the developer?

**Comment by mattburman** [comment]
Also getting this

**Comment by azai91** [comment]
PR #22 should fix this issue. Closing task.
