### ISSUE TITLE
Sign In not working. 

### ISSUE THREAD

**Issue by alessandrodallafina** [azai91/alfred-drive-workflow#25]
Hey there, 

I've been using your amazing workflow for quite a while and now I wanted to reinstall it in another laptop. The login seems not working though. 

I can see the login page with all my Google accounts but the process gets stuck tight after I click "Allow" Alfred to access my Drive. It keeps on saying "Waiting for 127.0.0.1"

**Comment by sepehr** [comment]
I second this. 

After authentication, Google redirects me to `http://127.0.0.1:1337/?code=foobar` which yields a 404 error:

```
404 page not found
```

**Comment by ryanwalker118** [comment]
Same problem

**Comment by cahofmeyr** [comment]
I'm having the same issue

**Comment by kbrunswick** [comment]
This workflow looks cool, but I am having the same issue.

**Comment by sorbits** [comment]
Please upgrade to [version 2.0](https://github.com/azai91/alfred-drive-workflow/releases/latest).

The authentication code has been rewritten and should be much more robust.
