### ISSUE TITLE
Workflow not working?

### ISSUE THREAD

**Issue by bridgestew** [azai91/alfred-drive-workflow#3]
I really hope this isn't user error, as your workflow appears to be dead simple. The workflow is installed and first appears to be working as evidenced by the first screenshot:
<img width="613" alt="screenshot 2015-11-01 08 49 22" src="https://cloud.githubusercontent.com/assets/214928/10869206/90768294-8075-11e5-8ac0-2dd2e3c4bf66.png">

But as soon as I begin typing a file name, this is what happens:
<img width="616" alt="screenshot 2015-11-01 08 47 56" src="https://cloud.githubusercontent.com/assets/214928/10869202/6672f5b8-8075-11e5-896d-ac1f9b622274.png">

I'm on El Capitan. Is this just a compatibility issue with the new OS?

**Comment by azai91** [comment]
could you open the debug log then type the filename? 
<img width="851" alt="screenshot 2015-11-01 11 29 31" src="https://cloud.githubusercontent.com/assets/8272546/10870892/eac0462a-808b-11e5-99ce-bbaa60a4d735.png">

**Comment by bridgestew** [comment]
Starting debug for 'Google Drive'

[STDERR: alfred.workflow.input.scriptfilter] 18:52:12 workflow.py:2140 DEBUG    Workflow version : 0.4.0
18:52:12 workflow.py:1543 DEBUG    Reading settings from `/Users/bstewart/Library/Application Support/Alfred 2/Workflow Data/com.drive.azai91/settings.json` ...
18:52:12 workflow.py:2401 DEBUG    Update check not due
18:52:12 workflow.py:1778 DEBUG    Loading cached data from : /Users/bstewart/Library/Caches/com.runningwithcrayons.Alfred-2/Workflow Data/com.drive.azai91/__workflow_update_status.cpickle
18:52:12 workflow.py:2349 DEBUG    update_data : {u'available': False}
18:52:12 workflow.py:2331 DEBUG    Set last run version : 0.4.0
18:52:12 workflow.py:2176 DEBUG    Workflow finished in 0.028 seconds.
[STDERR: alfred.workflow.input.scriptfilter] 18:52:12 workflow.py:2140 DEBUG    Workflow version : 0.4.0
18:52:12 workflow.py:1543 DEBUG    Reading settings from `/Users/bstewart/Library/Application Support/Alfred 2/Workflow Data/com.drive.azai91/settings.json` ...
18:52:12 workflow.py:2401 DEBUG    Update check not due
18:52:12 workflow.py:1778 DEBUG    Loading cached data from : /Users/bstewart/Library/Caches/com.runningwithcrayons.Alfred-2/Workflow Data/com.drive.azai91/__workflow_update_status.cpickle
18:52:12 workflow.py:2349 DEBUG    update_data : {u'available': False}
18:52:12 workflow.py:2331 DEBUG    Set last run version : 0.4.0
18:52:12 workflow.py:2176 DEBUG    Workflow finished in 0.022 seconds.
[STDERR: alfred.workflow.input.scriptfilter] 18:52:12 workflow.py:2140 DEBUG    Workflow version : 0.4.0
18:52:12 workflow.py:1543 DEBUG    Reading settings from `/Users/bstewart/Library/Application Support/Alfred 2/Workflow Data/com.drive.azai91/settings.json` ...
18:52:12 workflow.py:2401 DEBUG    Update check not due
18:52:12 workflow.py:1778 DEBUG    Loading cached data from : /Users/bstewart/Library/Caches/com.runningwithcrayons.Alfred-2/Workflow Data/com.drive.azai91/__workflow_update_status.cpickle
18:52:12 workflow.py:2349 DEBUG    update_data : {u'available': False}
18:52:12 workflow.py:2331 DEBUG    Set last run version : 0.4.0
18:52:12 workflow.py:2176 DEBUG    Workflow finished in 0.021 seconds.

**Comment by durmaze** [comment]
i have the same exact problem.

Starting debug for 'Google Drive'

[STDERR: alfred.workflow.input.scriptfilter] 11:25:06 workflow.py:2140 DEBUG    Workflow version : 0.4.0
11:25:06 workflow.py:1543 DEBUG    Reading settings from `/Users/edurmaz/Library/Application Support/Alfred 2/Workflow Data/com.drive.azai91/settings.json` ...
11:25:06 workflow.py:2401 DEBUG    Update check not due
11:25:06 workflow.py:1778 DEBUG    Loading cached data from : /Users/edurmaz/Library/Caches/com.runningwithcrayons.Alfred-2/Workflow Data/com.drive.azai91/__workflow_update_status.cpickle
11:25:06 workflow.py:2349 DEBUG    update_data : {u'available': False}
11:25:06 workflow.py:2331 DEBUG    Set last run version : 0.4.0
11:25:06 workflow.py:2176 DEBUG    Workflow finished in 0.023 seconds.
[STDERR: alfred.workflow.input.scriptfilter] 11:25:06 workflow.py:2140 DEBUG    Workflow version : 0.4.0
11:25:06 workflow.py:1543 DEBUG    Reading settings from `/Users/edurmaz/Library/Application Support/Alfred 2/Workflow Data/com.drive.azai91/settings.json` ...
11:25:06 workflow.py:2401 DEBUG    Update check not due
11:25:06 workflow.py:1778 DEBUG    Loading cached data from : /Users/edurmaz/Library/Caches/com.runningwithcrayons.Alfred-2/Workflow Data/com.drive.azai91/__workflow_update_status.cpickle
11:25:06 workflow.py:2349 DEBUG    update_data : {u'available': False}
11:25:06 workflow.py:2331 DEBUG    Set last run version : 0.4.0
11:25:06 workflow.py:2176 DEBUG    Workflow finished in 0.023 seconds.

**Comment by azai91** [comment]
Thank for being patient with me and helping make this workflow better. 

Did you sign in with the following command?

```
d > login
```

**Comment by bridgestew** [comment]
Yes, I did. I just received an update to the workflow when attempting to login again. That seems to have fixed the issue.

Thanks!

**Comment by azai91** [comment]
Awesome. Feel free to star the repo if you the workflow :)

**Comment by PatrickPro** [comment]
Downloaded the most recent version (v1.0) and currently encountering exactly the same issues - any idea how to fix this?

Can't even login - no debug output is shown. I'm on el Cap.

// EDIT: After restarting it works ;) :+1:

**Comment by azai91** [comment]
![](https://assets-cdn.github.com/images/icons/emoji/unicode/1f44d.png)
