### ISSUE TITLE
Actions don't launch in the Browser

### ISSUE THREAD

**Issue by Jawwads** [azai91/alfred-drive-workflow#34]
@azai91, I recently just updated to the latest version. However, after updating, any of my actions do not launch in the browser. That is; 

- When I search, and hit "enter" key it does not open it in the browser (it used to work before and I have been using for a long time) 
- The same is true when I type command for new document "d new name" and hit enter, it does not open in the browser (before it worked fine with the older command of >) 

Please help and thank you so very much for this awesome extension!

**Comment by sorbits** [comment]
1. When you use `new document` is the document being created? I.e. it is only the final step that fails.

2. Can you go to Alfred → Workflows → Google Drive and double-click the top “Run Script” box, it shows the following script:

        if [[ "$action" == '--open' ]]
          then open "$1"
          else ./google-drive.rb "$action" "$1" --name "$name"
        fi

    Can you change this to:

        if [[ "$action" == '--open' ]]
          then echo "$1" >> /tmp/urls.log && /usr/bin/open "$1"
          else ./google-drive.rb "$action" "$1" --name "$name"
        fi

    Just adding the full path for the `open` shell command and also log the URL being opened to `/tmp/urls.log`.

    If it still fails to open after using full path to `open`, please check contents of `/tmp/urls.log`.

**Comment by sorbits** [comment]
Closing this issue due to lack of response.

**Comment by Jawwads** [comment]
Sorry for the late reply. This still does not work for me. I have tried the above solution.

**Comment by Jawwads** [comment]
I also don't have anything or urls.log file in my tmp directory.

**Comment by sorbits** [comment]
What version of Alfred are you using?

**Comment by sorbits** [comment]
See issue #42

**Comment by Jawwads** [comment]
I am using the latest version of alfred.

**Comment by sorbits** [comment]
Please open Alfred Preferences and quote the actual version number you 
see there.
