### ISSUE TITLE
[request] Kiwi for Gmail

### ISSUE THREAD

**Issue by DanitiKain** [azai91/alfred-drive-workflow#36]
Can you make this so it works and opens docs in kiwi for gmail.

**Comment by sorbits** [comment]
What does that mean?

I did a quick search and Kiwi seems to be a Mac app that makes it so that `mailto:` links are sent to Gmail, I do not understand what this has to do with Google Docs or Alfred.

**Comment by DanitiKain** [comment]
The whole G Suite runs inside a kiwi windows separate from the browser.  So having it open in there would be helpful vs using another browser tab for a google doc.  This makes it function more like a office application.  Kiwi is much more than just a gmail tool.

**Comment by sorbits** [comment]
Can you open urls in Kiwi from a terminal?

For example using: `open -b «kiwi’s bundle identifier» 
http://example.org`

If that is possible, then this workflow can be made to use the same 
scheme.

See issue #35 for more details.

If you do not know about the `open` shell command or bundle identifiers 
then I suggest you ask the support team at Kiwi.

**Comment by DanitiKain** [comment]
Hello Brian,

Thank you for contacting us. Unfortunately, the development team say this is not possible. It has been added to the list of feature requests that they will look into, though. 
Best Regards,

Manny Santiago
Customer Support Representative
Zive, Inc.

**Comment by sorbits** [comment]
Thanks for the follow-up, I am closing this issue as it sounds like there is nothing we can do to work with Kiwi.

When they implement URL support, it should be possible to configure the `open_args` workflow variable similar to how it is already done for Chrome, Firefox, and Safari (see the _Configuration_ section of the ReadMe).
