### ISSUE TITLE
Newest Version of Alfred Won't Login

### ISSUE THREAD

**Issue by DanitiKain** [azai91/alfred-drive-workflow#37]
I am trying d > login and also trying to get it to open default browser to login and it will not do so.  Is there another way to authenticate to google drive.

**Comment by sorbits** [comment]
There is no `d > login` — try `d anything`, does that not bring up an authentication page in your default browser?

If you wish to login using another browser, copy/paste the URL.

**Comment by DanitiKain** [comment]
I rebooted and seems that after typing d anything it finally worked and asked me to login.
