### ISSUE TITLE
name changes in google drive documents

### ISSUE THREAD

**Issue by Samelot** [azai91/alfred-drive-workflow#4]
Hello, I've noticed an issue with this workflow properly seeing files I've renamed in Google Drive.

I had a file named "Tunnel Tutorial Guide" and renamed it to "SpaceStationTut", but I after doing so, I can only see "Tunnel Tutorial Guide" in the list that Alfred produces. If I do select "Tunnel Tutorial Guide", it does in fact bring me to the proper file ("SpaceStationTut"). 

Is there a way to clear the cache?

**Comment by azai91** [comment]
The cache is set by default to one day. I will add a feature that will allow you to reset (and set the duration of the cache). I will update you when when I push it.

**Comment by azai91** [comment]
Updated! Let me know your thoughts!

**Comment by Samelot** [comment]
Works awesome. Great work man, I'm finding this to be very useful.
