### ISSUE TITLE
Actions don't launch in the Browser

### ISSUE THREAD

**Issue by piyushmakhija** [azai91/alfred-drive-workflow#42]
Using v2.1
Chrome Version 61.0.3163.91
Successfully signed in using Chrome  - same version.

<img width="1077" alt="screen shot 2017-09-19 at 03 07 42" src="https://user-images.githubusercontent.com/5974717/30565983-e5191330-9ce7-11e7-90ad-e6594e33b4d0.png">

**Comment by sorbits** [comment]
What version of Alfred are you using?

**Comment by piyushmakhija** [comment]
Alfred v3.3.1

**Comment by sorbits** [comment]
Please upgrade to version 3.4.1.
