### ISSUE TITLE
Broken on OSx 10.13.1 (17B48)

### ISSUE THREAD

**Issue by nerdgirl** [azai91/alfred-drive-workflow#46]
Workflow opens a new blank browser window when trying to open a file. Only happening since update of OSx.

**Comment by sorbits** [comment]
The workflow uses the `open` shell command with a URL, to open the document in your default browser.

So the most likely explanation is to be found with your browser, as if we did not give a valid `https` URL to the `open` command, no browser window should open at all.

What browser is opening? What is shown in the location field of the browser? Is your browser logged into your Google Drive (i.e. has the proper authentication cookie)?

**Comment by sorbits** [comment]
Closing due to lack of response from OP.
