### ISSUE TITLE
redirecting to 127.0.0.1 not working

### ISSUE THREAD

**Issue by la32094uf** [azai91/alfred-drive-workflow#5]
After updating to the latests 0.6, granting acces,

<img width="535" alt="schermafbeelding 2015-11-19 om 20 48 05" src="https://cloud.githubusercontent.com/assets/11858721/11282298/dcbea68a-8efe-11e5-987e-6126afa81209.png">

 i still get a redirect to a non-working 127.0.0.1:1337 page

<img width="658" alt="schermafbeelding 2015-11-19 om 20 48 46" src="https://cloud.githubusercontent.com/assets/11858721/11282315/f43499aa-8efe-11e5-8757-05a43ed1e0de.png">

**Comment by azai91** [comment]
Can you open the workflow (right click on the workflow and click open in finder) and then paste in the text inside the nohup.out. If possible (not necessary), can you run the following line in your command line (in the root of the source files), 

```
python server.py
```

and let me know what is printed the console?

Thanks!

**Comment by ralphcallaway** [comment]
running into the same issue, mac os x 10.10.5, alfred v2.8.4 (437)

checked `nohup.out`, and it's empty

ran `python server.py` and then refreshed the browser windows with the google authorization code, got this in the terminal output

```
14:04:49 workflow.py:2471 DEBUG    Password exists : com.drive.azai91:drive_access_token
14:04:49 workflow.py:2518 DEBUG    Got password : com.drive.azai91:drive_access_token
14:04:49 workflow.py:2540 DEBUG    Deleted password : com.drive.azai91:drive_access_token
14:04:49 workflow.py:2481 DEBUG    save_password : com.drive.azai91:drive_access_token
14:04:49 workflow.py:2471 DEBUG    Password exists : com.drive.azai91:drive_refresh_token
14:04:49 workflow.py:2518 DEBUG    Got password : com.drive.azai91:drive_refresh_token
14:04:49 workflow.py:2540 DEBUG    Deleted password : com.drive.azai91:drive_refresh_token
14:04:49 workflow.py:2481 DEBUG    save_password : com.drive.azai91:drive_refresh_token
14:04:50 workflow.py:2518 DEBUG    Got password : com.drive.azai91:drive_access_token
```

tried running login from alfred a couple times, which didn't generate any output, and timed out again

at some point things started working, yay! i was doing a bunch of different things, but seems like doing the following should work for people
- open alfred
- "d >" -> login
- complete google oauth flow
- wait for browser to time out at 127.0.0.1
- open terminal and run `python server.py`
- refresh browser window
- be patient
- try it out

**Comment by ralphcallaway** [comment]
fingers crossed this could get re-opened with this info :)

**Comment by pkuczynski** [comment]
Might be connected to #16
