### ISSUE TITLE
Open Locally?

### ISSUE THREAD

**Issue by TechRemarker** [azai91/alfred-drive-workflow#51]
Is there a way to open the local copy of files (but search with Google Drive search)? That is Spotlight (and Alfred since it uses Spotlight's database), don't typically find what I'm looking for. Versus Google search which always does in the browser. A big part is it shows any and all results with a certain word or phrase rather than just the top 10, etc. More importantly, Google indexes content in PDFs and Images such as scans. 

Since Google doesn't have Googe Search for the Mac (not anymore at least). I was thinking, I could sync all my files to Google Drive, and then could use Google Drive search or Google Cloud Search to file files on my mac. The issue is it would open a copy in the browser or require me to download a copy which wouldn't be helpful. Would need to open the local file on my mac, no matter the format or app. 

Is there any way this app could help with that or any others that could? Files are located in a certain folder, and Google Drive knows that folder structure so one would think there would be some way of accomplishing it but not sure if that currently exists.

**Comment by sorbits** [comment]
> Is there any way this app could help with that or any others that could? Files are located in a certain folder, and Google Drive knows that folder structure so one would think there would be some way of accomplishing it but not sure if that currently exists.

This “app” is just a workflow for Alfred that feeds Alfred with a list of files on Google Drive, it does not do any actual content searching or leverages Google’s (content) search features.

As for your general problem, I think you should try Spotlight search directly, since that should do content search, I think Alfred only uses a subset of spotlight, e.g. it does spotlight queries to get at your contacts and installed applications, but by default I do not think it does any content searching.

**Comment by TechRemarker** [comment]
Thanks for getting back and clarifying the features of this plugin. 

Using Spotlight directly in my case won't help since it doesn't search more than Alfred. Alfred actually is able to search inside content like Spotlight you just have to either start with "in" or just change the setting in Alfred. Though in my case, the issue is not being able to search in PDF's or Images. Spotlight doesn't do that, and Alfred doesn't since it uses Spotlights database. Where is google indexes all PDF and even images text content.

For now sounds like the best bet is to simply use a custom search feature in Alfred for https://drive.google.com/drive/search?q={query} to leverage Google's search functionality, and then will simply have to look at the location and then manually open that file locally, until a prettier solution is developed.  If anyone later reads this and is looking for a similar Drive solution to note there is this official Google Drive plugin: https://chrome.google.com/webstore/detail/application-launcher-for/lmjegmlicamnimmfhcmpkclmigmmcbeh which requires Chrome and seems to offer open with locally functionality which in combination with Google Drive Search in Alfred would work, but that open with only works with a few select file types so not a real solution. Thanks again!
