### ISSUE TITLE
Add Google Drawings to supported file types 

### ISSUE THREAD

**Issue by justinjm** [azai91/alfred-drive-workflow#55]
Would it be possible to add [Google Drawings](https://support.google.com/docs/answer/179740?co=GENIE.Platform%3DDesktop&hl=en) to the list of [Supported File Types](https://github.com/azai91/alfred-drive-workflow#supported-files-types) ?

Would be super helpful to have this :)

Thank you for creating a great workflow that I use countless times every day.

Justin

**Comment by sorbits** [comment]
See [this comment](https://github.com/azai91/alfred-drive-workflow/issues/13#issuecomment-325277361) of issue #13.

Closing as duplicate.
