### ISSUE TITLE
No Results are Showing for The Search

### ISSUE THREAD

**Issue by Jawwads** [azai91/alfred-drive-workflow#56]
**Actual Behavior:** It no longer shows results when I do a search. See image below: 

**Expected Behavior:** It displays results for the search as it did before. I am a regular and long-time user (thank you!) and it just suddenly stoped working. 

I have already tried 
- Installing / Re-Installing the Workflow
- Re-connecting my google account
- Re-installing alfred 
- Clearning application cache

**Comment by sorbits** [comment]
Try sign out/in again, the log shows:

	[2018-03-29 11:56:11.159]  [INFO] Refresh token added to keychain
	[2018-03-29 11:56:11.218]  [INFO] Access token added to keychain, expires in 3600 seconds
	[2018-03-29 11:56:11.218] [DEBUG] Stopping HTTP server
	[2018-03-29 11:56:11.424] [ERROR] Server returned 403 when fetching items from Google Drive: 

So it gets an access token but then a 403 (permission denied) when trying to use it.

**Comment by Jawwads** [comment]
@sorbits, I have tried that numerous times. It does not work. I have double checked the firewall etc.

**Comment by Jawwads** [comment]
Please let me know if you have any other ideas. I am out of options to try.

**Comment by sorbits** [comment]
Try on another computer, another user account, and (log in to) another 
Google account.

Create another Google account if you don’t already have one (after 
connecting to this, you can just test the New Document action rather 
than add documents to this account and see if they show up in the list).

**Comment by Jawwads** [comment]
Thanks! It works with other computers and different google account. This account is the only one giving me trouble. I think I know why. Thank you for your help!
