### ISSUE TITLE
Information request: security with allowing access?

### ISSUE THREAD

**Issue by jzadra** [azai91/alfred-drive-workflow#57]
When logging in, it wants to give access to all my files to "Alfred Drive Workflow".  Does this open my drive security to a 3rd party?  I see that a CLIENT_ID and CLIENT_SECRET is predifined in the python script.  Is there any documentation on who gains access and security in general using this workflow?

**Comment by sorbits** [comment]
The script needs access to your drive in order to show you the list of files.

The access token is stored in your keychain and not sent to a third party.
