### ISSUE TITLE
Not showing all files

### ISSUE THREAD

**Issue by davidkaneda** [azai91/alfred-drive-workflow#6]
This extension would be super useful for me, but for some reason it's missing a bunch of results... Has anyone else run into this before? I get much more robust options when I search in Drive directly-

**Comment by azai91** [comment]
What type of files are you looking for? Right now it is configured to search for docs, sheets, and slides.

**Comment by davidkaneda** [comment]
Ah definitely. Just looking for docs. Here's a (heavily redacted) sample:

![screen shot 2015-12-16 at 3 46 57 pm](https://cloud.githubusercontent.com/assets/21713/11857409/dc7d4eba-a40c-11e5-9f93-72b43d9a40c1.png)
![screen shot 2015-12-16 at 3 43 39 pm](https://cloud.githubusercontent.com/assets/21713/11857404/cbc665fc-a40c-11e5-9fb8-39ba5be97cc2.png)

**Comment by davidkaneda** [comment]
Perhaps it's just the quantity of docs in my Drive? (I work at Google, so there's quite a few...)

**Comment by azai91** [comment]
I made a few updates that should hopefully address the issue. You should receive a request for an update automatically, but if not, download the latest version [here](https://github.com/azai91/alfred-drive-workflow/releases/tag/v1.0). Once your version is updated, you may need to reset your cache by running `d > Clear cache` in Alfred. Please let me know if you are able to see all your files after this update!

**Comment by davidkaneda** [comment]
That fixed it! Odd that it requires pagination with the list size of 1000, but I don't the details of the search... May be worth noting it's noticeably slower now (though it works, and will still be super useful to me). As a thank you, I [updated the file icons for ya](https://github.com/azai91/alfred-drive-workflow/pull/7) :)

**Comment by azai91** [comment]
Thank you. Looks great!
