### ISSUE TITLE
Add license?

### ISSUE THREAD

**Issue by cdeutsch** [azai91/alfred-drive-workflow#60]
How is this code licensed?

I modified it to create a Google Calendar "Quick Add" Alfred workflow and I'd like to release it, but only if that's ok with you.

Nice work on this workflow 👍

**Comment by sorbits** [comment]
The repository was created by @azai91 so I feel he should be the one to add a repository-wide `LICENSE`, but as I created `google-drive.rb` more or less from scratch, and I assume that is the file you want to modify, I added the MIT license to just this file.

**Comment by azai91** [comment]
added
