### ISSUE TITLE
Re-install Issue

### ISSUE THREAD

**Issue by brandonwentland** [azai91/alfred-drive-workflow#9]
Today I accidentally installed the extension even though it was already installed.  Now none of the commands (including login, logout) work.

I tried deleting and reinstalling but no luck.

Screencast: http://cl.ly/1K0b2r030n0R

**Comment by eikebartels** [comment]
same for me

**Comment by azai91** [comment]
this may be an issue with the operating system interacting with the python library. did you redownload the latest version of the workflow from github[https://github.com/azai91/alfred-drive-workflow/releases]?

**Comment by eikebartels** [comment]
downloading the latest version didnt solve the issue.

**Comment by sorbits** [comment]
Please try [version 1.4 available here](https://github.com/sorbits/alfred-drive-workflow/releases/tag/v1.4)

I made a lot of improvements (complete rewrite) and also added verbose logging, so if there is still a problem, it should be easier to debug.

**Comment by sorbits** [comment]
There is now [version 2.0](https://github.com/azai91/alfred-drive-workflow/releases/latest) (which supersede v1.4 mentioned above).

Please open a new issue if you are having any problems using this updated version of the workflow.
